# Generated by Django 4.0.2 on 2022-09-01 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bar', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diamond',
            name='img',
        ),
        migrations.RemoveField(
            model_name='heart',
            name='img',
        ),
        migrations.RemoveField(
            model_name='oblong',
            name='img',
        ),
        migrations.RemoveField(
            model_name='oval',
            name='img',
        ),
        migrations.RemoveField(
            model_name='round',
            name='img',
        ),
        migrations.RemoveField(
            model_name='square',
            name='img',
        ),
        migrations.RemoveField(
            model_name='triangle',
            name='img',
        ),
        migrations.AddField(
            model_name='diamond',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='heart',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='oblong',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='oval',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='round',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='square',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='triangle',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
